backend/src/main/java/com/example/backend/product/model/Product.java

상품 외의 테이블과 매핑 추가 및 각 항목 idx 이름 단순 idx에서 변경(ex: idx -> productIdx)

상품 외의 테이블과 매핑 추가

---

backend/src/main/java/com/example/backend/user/model/User.java
backend/src/main/java/com/example/backend/user/model/UserProduct.java

[Fix] fix idx number type

---

backend/build.gradle
backend/src/main/java/com/example/backend/board/model/Board.java
backend/src/main/java/com/example/backend/order/model/OrderDetail.java
backend/src/main/java/com/example/backend/product/controller/ProductController.java
backend/src/main/java/com/example/backend/product/model/Product.java
backend/src/main/java/com/example/backend/product/model/ProductImage.java
backend/src/main/java/com/example/backend/product/model/dto/ProductRequestDto.java
backend/src/main/java/com/example/backend/product/model/dto/ProductResponseDto.java
backend/src/main/java/com/example/backend/product/model/spec/CpuSpec.java
backend/src/main/java/com/example/backend/product/model/spec/GpuSpec.java
backend/src/main/java/com/example/backend/product/model/spec/HddSpec.java
backend/src/main/java/com/example/backend/product/model/spec/RamSpec.java
backend/src/main/java/com/example/backend/product/model/spec/SsdSpec.java
backend/src/main/java/com/example/backend/user/model/UserProduct.java
backend/src/main/java/com/example/backend/wishlist/model/Wishlist.java

ProductController Swagger 1차 적용(기능 미구현)

Swagger UI를 위한 build.gradle 추가

---

.idea/gradle.xml
backend/src/main/java/com/example/backend/product/controller/ProductController.java
backend/src/main/java/com/example/backend/product/model/dto/CpuSpecDto.java
backend/src/main/java/com/example/backend/product/model/dto/GpuSpecDto.java
backend/src/main/java/com/example/backend/product/model/dto/HddSpecDto.java
backend/src/main/java/com/example/backend/product/model/dto/ProductResponseDto.java
backend/src/main/java/com/example/backend/product/model/dto/RamSpecDto.java
backend/src/main/java/com/example/backend/product/model/dto/SsdSpecDto.java
backend/src/main/java/com/example/backend/product/repository/ProductRepository.java
backend/src/main/java/com/example/backend/product/service/ProductService.java

필터를 제외한 상품 관련 상세 조회, 리스트 조회, 검색 기능 구현

간단한 CRUD 기능을 포함한 Service 및 Dto 업데이트

---

backend/src/main/java/com/example/backend/coupon/controller/CouponController.java
backend/src/main/java/com/example/backend/order/controller/OrderController.java

쿠폰과 주문 컨트롤러 swagger ui를 위한 기능 추가

---

backend/src/main/java/com/example/backend/cart/controller/CartController.java
backend/src/main/java/com/example/backend/wishlist/controller/WishlistController.java

장바구니와 위시리스트 swagger ui를 위한 기능 추가

---

backend/src/main/java/com/example/backend/config/filter/JwtFilter.java
backend/src/main/resources/application.yml

application.yaml DB 및 JWT 토큰 관련 환경변수 설정이 되도록 기초적으로 변경했습니다.

[Fix] fix application setting yaml

---

backend/src/main/java/com/example/backend/config/SecurityConfig.java

Swagger ui 실행 시 로그인을 요구하지 않도록 변경

Swagger ui 로그인 요구하지 않도록 변경

---

backend/src/main/java/com/example/backend/board/controller/LikesController.java
backend/src/main/java/com/example/backend/cart/controller/CartController.java
backend/src/main/java/com/example/backend/comment/controller/CommentController.java
backend/src/main/java/com/example/backend/coupon/controller/CouponController.java
backend/src/main/java/com/example/backend/product/controller/ProductController.java
backend/src/main/java/com/example/backend/wishlist/controller/WishlistController.java

Swagger ui 설명 누락되어 있는 컨트롤러 설명 추가

Swagger ui 설명 추가

---

backend/src/main/java/com/example/backend/coupon/controller/CouponController.java
backend/src/main/java/com/example/backend/coupon/controller/UserCouponController.java
backend/src/main/java/com/example/backend/user/controller/UserController.java

사용자에게 할당된 쿠폰 관련 컨트롤러 추가

---

backend/src/main/java/com/example/backend/product/controller/ProductController.java
backend/src/main/java/com/example/backend/product/model/Product.java
backend/src/main/java/com/example/backend/product/service/ProductService.java

관리자 기능 - 상품 등록, 삭제, 수정 기능 추가

---

backend/src/main/java/com/example/backend/cart/controller/CartController.java
backend/src/main/java/com/example/backend/cart/model/CartItem.java
backend/src/main/java/com/example/backend/cart/model/dto/CartItemRequestDto.java
backend/src/main/java/com/example/backend/cart/repository/CartRepository.java
backend/src/main/java/com/example/backend/cart/service/CartService.java

장바구니 목록 조회, 항목 추가, 항목 삭제 기능 구현

장바구니 기능 컨트롤러 변경 및 서비스 구현

---

backend/src/main/java/com/example/backend/board/controller/LikesController.java
backend/src/main/java/com/example/backend/cart/controller/CartController.java
backend/src/main/java/com/example/backend/cart/model/CartItem.java
backend/src/main/java/com/example/backend/cart/model/dto/CartItemUpdateRequestDto.java
backend/src/main/java/com/example/backend/cart/service/CartService.java

장바구니 상품 수량 변경 가능하도록 기능 추가.
만약 수량이 0 이하라면 목록에서 삭제하도록 변경.

장바구니 상품 수량 변경 기능 추가

---

backend/src/main/java/com/example/backend/config/PortoneConfig.java
backend/src/main/java/com/example/backend/order/controller/OrderController.java
backend/src/main/java/com/example/backend/order/model/OrderDetail.java
backend/src/main/java/com/example/backend/order/model/Orders.java
backend/src/main/java/com/example/backend/order/model/dto/OrderDetailResponseDto.java
backend/src/main/java/com/example/backend/order/model/dto/OrderResponseDto.java
backend/src/main/java/com/example/backend/order/repository/OrderRepository.java
backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/main/java/com/example/backend/util/HttpClientUtil.java

BTS - 84, 85 - [feat] 사용자의 주문 내역 조회, 주문 취소 및 환불 기능 추가
BTS - 118, 119 - [feat] portone api를 활용한 카카오 결제 로직 추가

BTS-91[제품 주문] - 주문 기능 구현

---

backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/main/resources/application.yml

BTS-119 [fix] - portone api에 필요한 환경변수 설정

---

backend/src/main/java/com/example/backend/product/model/Product.java
backend/src/main/java/com/example/backend/review/controller/ReviewController.java
backend/src/main/java/com/example/backend/review/model/Review.java
backend/src/main/java/com/example/backend/review/model/dto/ReviewRequestDto.java
backend/src/main/java/com/example/backend/review/model/dto/ReviewResponseDto.java
backend/src/main/java/com/example/backend/review/repository/ReviewRepository.java
backend/src/main/java/com/example/backend/review/service/ReviewService.java

BTS-130, 131, 132 [feat] - 리뷰 기능 구현

---

backend/src/main/java/com/example/backend/admin/controller/StatisticController.java
backend/src/main/java/com/example/backend/admin/model/StatisticsResponseDto.java
backend/src/main/java/com/example/backend/admin/model/TopWishListDto.java
backend/src/main/java/com/example/backend/admin/model/ViewRequestDto.java
backend/src/main/java/com/example/backend/admin/service/StatisticsService.java
backend/src/main/java/com/example/backend/coupon/controller/CouponController.java
backend/src/main/java/com/example/backend/coupon/model/Coupon.java
backend/src/main/java/com/example/backend/coupon/model/dto/request/CategoryCouponCreateRequest.java
backend/src/main/java/com/example/backend/coupon/model/dto/request/CategoryCouponCreateRequestDto.java
backend/src/main/java/com/example/backend/coupon/model/dto/request/EventCouponCreateRequest.java
backend/src/main/java/com/example/backend/coupon/model/dto/request/UserCouponCreateRequestDto.java
backend/src/main/java/com/example/backend/coupon/model/dto/response/CouponInfoDto.java
backend/src/main/java/com/example/backend/coupon/model/dto/response/CouponListResponseDto.java
backend/src/main/java/com/example/backend/coupon/repository/CouponRepository.java
backend/src/main/java/com/example/backend/coupon/repository/UserCouponRepository.java
backend/src/main/java/com/example/backend/coupon/service/CouponService.java
backend/src/main/java/com/example/backend/order/repository/OrderDetailRepository.java
backend/src/main/java/com/example/backend/order/repository/OrderRepository.java
backend/src/main/java/com/example/backend/user/repository/UserRepository.java
backend/src/main/java/com/example/backend/wishlist/repository/WishlistRepository.java

관리자 통계 일부와 쿠폰 등록 및 목록 조회입니다.
#BTS-94
#BTS-99

[Feat] 관리자 통계 및 쿠폰 등록, 목록 확인 추가 

---

backend/src/main/java/com/example/backend/global/response/responseStatus/ProductResponseStatus.java
backend/src/main/java/com/example/backend/product/controller/ProductController.java

상품 목록, 상품 상세 조회, 상품 검색, 상품 필터링, 상품 등록, 삭제, 수정

BTS-54, 122, 123 [feat] - 제품 관련 기능 BaseResponse로 묶어서 전달하도록 수정

---

backend/src/main/java/com/example/backend/global/response/responseStatus/OrderResponseStatus.java
backend/src/main/java/com/example/backend/order/controller/OrderController.java
backend/src/main/java/com/example/backend/product/controller/ProductController.java

상품 주문, 상품 결제, 주문 취소, 주문 내역 조회, 주문 상세 조회, 환불 요청

BTS-91 [feat] - 결제 관련 기능 BaseResponse로 묶어서 전달하도록 수정

---

backend/src/main/java/com/example/backend/cart/controller/CartController.java
backend/src/main/java/com/example/backend/cart/model/dto/CartItemUpdateResponseDto.java
backend/src/main/java/com/example/backend/cart/service/CartService.java
backend/src/main/java/com/example/backend/global/response/responseStatus/CartResponseStatus.java
backend/src/main/java/com/example/backend/global/response/responseStatus/ReviewResponseStatus.java
backend/src/main/java/com/example/backend/global/response/responseStatus/WishlistResponseStatus.java
backend/src/main/java/com/example/backend/review/controller/ReviewController.java
backend/src/main/java/com/example/backend/review/model/dto/ReviewDeleteResponseDto.java
backend/src/main/java/com/example/backend/review/service/ReviewService.java
backend/src/main/java/com/example/backend/wishlist/controller/WishlistController.java
backend/src/main/java/com/example/backend/wishlist/model/dto/WishlistToggleResponseDto.java
backend/src/main/java/com/example/backend/wishlist/service/WishlistService.java

BTS-110, 111, 112, 117 - 장바구니 관련 기능
BTS-129  - 리뷰 관련 기능
BTS-125 - 위시리스트 관련 기능

담당 기능 BaseResponse로 묶어서 전달하도록 수정

---

backend/build.gradle
backend/src/main/java/com/example/backend/admin/controller/StatisticController.java
backend/src/main/java/com/example/backend/admin/model/StatisticsResponseDto.java
backend/src/main/java/com/example/backend/admin/model/TopSalesDto.java
backend/src/main/java/com/example/backend/admin/service/StatisticsService.java
backend/src/main/java/com/example/backend/order/repository/OrderDetailRepository.java
backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/main/java/com/example/backend/product/controller/ProductController.java
backend/src/main/java/com/example/backend/product/model/Product.java
backend/src/main/java/com/example/backend/product/model/dto/ProductRequestDto.java

* 제품 관련 통계 중 조회/검색 제외하고 백엔드 API 구현
* Product 내 잘못된 어노테이션 수정

[Feat] 관리자 통계 데이터를 프론트와 연결 중

---

backend/src/main/java/com/example/backend/coupon/controller/CouponController.java
backend/src/main/java/com/example/backend/coupon/model/dto/request/AllCouponCreateRequestDto.java
backend/src/main/java/com/example/backend/coupon/model/dto/request/UserCouponCreateRequestDto.java
backend/src/main/java/com/example/backend/coupon/model/dto/response/CouponInfoDto.java
backend/src/main/java/com/example/backend/coupon/model/dto/response/CouponListResponseDto.java
backend/src/main/java/com/example/backend/coupon/service/CouponService.java

[Fix] 날짜 및 제품 연관관계 오류 수정

---

backend/src/main/java/com/example/backend/product/controller/ProductController.java
backend/src/main/java/com/example/backend/product/model/Product.java
backend/src/main/java/com/example/backend/product/model/dto/ProductFilterRequestDto.java
backend/src/main/java/com/example/backend/product/model/dto/ProductRequestDto.java
backend/src/main/java/com/example/backend/product/model/dto/ProductResponseDto.java
backend/src/main/java/com/example/backend/product/service/ProductService.java

BTS-54, 138 할인율 컬럼 추가
ProductController BaseResponse 송신 하도록 자료형 변경

[feat] - 할인율 항목 추가

---

backend/src/main/java/com/example/backend/coupon/service/CouponService.java
backend/src/main/java/com/example/backend/product/model/Product.java
backend/src/main/java/com/example/backend/product/model/dto/ProductRequestDto.java
backend/src/main/java/com/example/backend/product/repository/CpuSpecRepository.java
backend/src/main/java/com/example/backend/product/repository/GpuSpecRepository.java
backend/src/main/java/com/example/backend/product/repository/HddSpecRepository.java
backend/src/main/java/com/example/backend/product/repository/RamSpecRepository.java
backend/src/main/java/com/example/backend/product/repository/SsdSpecRepository.java
backend/src/main/java/com/example/backend/product/service/ProductService.java

이미지 URL를 제외하고 모든 데이터를 DB에 저장할 수 있음
S3에 이미지 저장하는 방법을 확인하고 2차 강화에 들어갈 예정임
#BTS-53

[Feat] 제품 등록 기능 1차 강화

---

backend/src/main/java/com/example/backend/product/controller/ProductController.java

BaseResponse 사용하도록 수정(ResponseEntity 사용하지 않는다)
통일된 JSON을 전달하기 위해.

BaseResponse 사용하도록 수정(ResponseEntity 사용하지 않는다)

---

backend/src/main/java/com/example/backend/admin/controller/StatisticController.java
backend/src/main/java/com/example/backend/coupon/controller/CouponController.java
backend/src/main/java/com/example/backend/product/controller/ProductImageController.java
backend/src/main/java/com/example/backend/product/model/dto/ProductImageSaveRequestDto.java
backend/src/main/java/com/example/backend/product/model/dto/ProductRequestDto.java
backend/src/main/java/com/example/backend/product/model/dto/ProductResponseDto.java
backend/src/main/java/com/example/backend/product/repository/ProductImageRepository.java
backend/src/main/java/com/example/backend/product/service/ProductImageService.java
backend/src/main/java/com/example/backend/product/service/ProductService.java
backend/src/main/resources/application.yml

AWS S3 정보를 환경 변수로 받도록 application.yml에 수정이 들어갔습니다.
이미지는 사실 여러 개 등록해도 잘 작동합니다

[Feat] 제품 등록 마무리 및 제품 수정을 위해 기존 등록 정보 불러오기

---

backend/src/main/java/com/example/backend/common/dto/ProductSummaryDto.java

[fix] BTS-111 재고 항목이 빠져서 항상 재고 불충분으로 에러 발생하는 오류 수정

상품 요약 정보 전달에 재고 수량도 전달하도록 변경

---

backend/src/main/java/com/example/backend/common/dto/ProductSummaryDto.java
backend/src/main/java/com/example/backend/global/response/responseStatus/WishlistResponseStatus.java
backend/src/main/java/com/example/backend/wishlist/controller/WishlistController.java

BTS-125
위시리스트 사용자 인증 관련 기능 처리 추가 및 할인율 정보 추가

위시리스트 처리 로직 수정

---

backend/src/main/java/com/example/backend/wishlist/controller/WishlistController.java
backend/src/main/java/com/example/backend/wishlist/model/dto/WishlistResponseDto.java
backend/src/main/java/com/example/backend/wishlist/service/WishlistService.java

위시리스트 응답 dto 패키지 경로 오류 수정

---

backend/build.gradle
backend/src/main/java/com/example/backend/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/example/backend/global/exception/UserException.java
backend/src/main/java/com/example/backend/global/response/responseStatus/UserResponseStatus.java
backend/src/main/java/com/example/backend/user/controller/UserController.java
backend/src/main/java/com/example/backend/user/model/dto/request/EmailRequestDto.java
backend/src/main/java/com/example/backend/user/model/dto/request/SignupRequestDto.java
backend/src/main/java/com/example/backend/user/model/dto/request/ValidateEmailRequestDto.java
backend/src/main/java/com/example/backend/user/service/EmailVerifyService.java
backend/src/main/java/com/example/backend/user/service/UserService.java
backend/src/main/resources/application.yml

BTS-36 [Feat] 이메일 인증

---

backend/src/main/java/com/example/backend/global/response/responseStatus/ProductResponseStatus.java
backend/src/main/java/com/example/backend/product/controller/ProductImageController.java
backend/src/main/java/com/example/backend/product/model/ProductImage.java
backend/src/main/java/com/example/backend/product/model/spec/CpuSpec.java
backend/src/main/java/com/example/backend/product/model/spec/GpuSpec.java
backend/src/main/java/com/example/backend/product/model/spec/HddSpec.java
backend/src/main/java/com/example/backend/product/model/spec/RamSpec.java
backend/src/main/java/com/example/backend/product/model/spec/SsdSpec.java
backend/src/main/java/com/example/backend/product/service/ProductImageService.java
backend/src/main/java/com/example/backend/product/service/ProductService.java

* 제품 삭제 가능
* 제품 삭제 가능한 경우와 불가능한 경우를 상정해야 할 상황이므로 토의 필요
* 제품 수정 기능은 이미지 제외하고 전부 수정 가능
* 이미지의 경우 이전에 업로드한 사진을 남기는 것이 좋은지 토의 필요

[Feat] 제품 수정 및 삭제 기능 추가

---

backend/src/main/java/com/example/backend/cart/controller/CartController.java
backend/src/main/java/com/example/backend/cart/model/Cart.java
backend/src/main/java/com/example/backend/cart/repository/CartItemRepository.java
backend/src/main/java/com/example/backend/cart/service/CartService.java
backend/src/main/java/com/example/backend/global/response/responseStatus/CartResponseStatus.java
backend/src/main/java/com/example/backend/wishlist/controller/WishlistController.java

BTS-148, 111, 112
장바구니 기능 로그인 되지 않았다면 예외 처리 추가, 장바구니 항목 추가 시 재고를 확인하는 로직 추가

장바구니 기능 로직 수정

---

backend/src/main/java/com/example/backend/cart/controller/CartController.java
backend/src/main/java/com/example/backend/cart/model/dto/CartItemUpdateResponseDto.java
backend/src/main/java/com/example/backend/cart/service/CartService.java

장바구니 비우기 기능 추가

---

backend/src/main/java/com/example/backend/global/response/responseStatus/UserResponseStatus.java
backend/src/main/java/com/example/backend/notification/model/NotificationType.java
backend/src/main/java/com/example/backend/notification/service/NotificationService.java

전체 공지용 NOTIFICATION과 사용자 쿠폰 발급 알림용 PERSONAL이 추가됩니다.

[Fix] 사라진 알림 열거형 다시 추가

---

backend/src/main/java/com/example/backend/order/controller/OrderController.java
backend/src/main/java/com/example/backend/order/model/dto/OrderVerifyRequestDto.java
backend/src/main/java/com/example/backend/order/repository/ShippingAddressRepository.java
backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/main/java/com/example/backend/util/HttpClientUtil.java

BTS-158 결제 검증 기능 추가(정상이라면 주문 상태 PLACED에서 PAID로 변경)
BTS-152 사용자의 배송정보 DB 저장

결제 기능 디테일 추가

---

backend/src/main/java/com/example/backend/global/response/responseStatus/OrderResponseStatus.java
backend/src/main/java/com/example/backend/order/service/OrderService.java

BTS-155 검증 성공 시 각 상품 해당 상품의 주문 수만큼 차감

[feat] 결제 성공 시 재고 차감

---

backend/src/main/java/com/example/backend/order/model/Orders.java
backend/src/main/java/com/example/backend/order/model/dto/OrderRequestDto.java
backend/src/main/java/com/example/backend/order/model/dto/OrderResponseDto.java
backend/src/main/java/com/example/backend/order/service/OrderService.java

BTS-154 배송비 확인 및 배송비가 포함된 가격 검증을 위한 로직 수정

[feat] 배송 방법, 배송비, 결제 방식 표시할 수 있도록 수정

---

backend/src/main/java/com/example/backend/order/controller/OrderController.java
backend/src/main/java/com/example/backend/order/repository/OrderRepository.java
backend/src/main/java/com/example/backend/order/service/OrderService.java

[feat] 마이페이지 주문 내역 확인 기능 추가

---

backend/src/main/java/com/example/backend/global/response/responseStatus/OrderResponseStatus.java
backend/src/main/java/com/example/backend/order/controller/OrderController.java
backend/src/main/java/com/example/backend/order/model/Orders.java
backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/main/java/com/example/backend/util/HttpClientUtil.java

[feat] 환불 기능 백엔드 추가

---

backend/src/main/java/com/example/backend/order/service/OrderService.java

BTS-85 REFUND_REQUESTED가 아니라면 환불하지 않도록 수정

[fix] 환불 요청에 주문 취소가 이루어지도록 수정

---

backend/src/main/java/com/example/backend/review/controller/ReviewController.java
backend/src/main/java/com/example/backend/review/model/dto/ReviewResponseDto.java
backend/src/main/java/com/example/backend/review/repository/ReviewRepository.java
backend/src/main/java/com/example/backend/review/service/ReviewService.java

BTS -130,162, 
로그인하지 않은 사람이 리뷰를 작성 했다면 의문의 유저 라고 공통 닉네임으로 전달하도록 수정

[fix] 상품별 리뷰 출력 기능 오류 수정

---

backend/src/main/java/com/example/backend/admin/controller/StatisticController.java
backend/src/main/java/com/example/backend/admin/service/StatisticsService.java
backend/src/main/java/com/example/backend/coupon/controller/CouponController.java
backend/src/main/java/com/example/backend/coupon/controller/UserCouponController.java
backend/src/main/java/com/example/backend/coupon/model/Coupon.java
backend/src/main/java/com/example/backend/coupon/model/UserCoupon.java
backend/src/main/java/com/example/backend/coupon/model/dto/response/CouponInfoDto.java
backend/src/main/java/com/example/backend/coupon/model/dto/response/MyCouponInfoResponseDto.java
backend/src/main/java/com/example/backend/coupon/repository/CouponRepository.java
backend/src/main/java/com/example/backend/coupon/repository/UserCouponRepository.java
backend/src/main/java/com/example/backend/coupon/service/CouponService.java
backend/src/main/java/com/example/backend/notification/controller/NotificationController.java
backend/src/main/java/com/example/backend/order/controller/OrderController.java
backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/main/java/com/example/backend/product/controller/ProductController.java
backend/src/main/java/com/example/backend/product/service/ProductImageService.java
backend/src/main/java/com/example/backend/product/service/ProductService.java

* 선착순 쿠폰 이벤트 생성 및 쿠폰 발행 추가
* 관리자용 API는 관리자만 접근 가능하도록 설정
* 통계 대시보드 오류 수정

[Feat] 쿠폰 및 주문 취소 관련 수정

---

backend/src/main/java/com/example/backend/global/response/responseStatus/ReviewResponseStatus.java
backend/src/main/java/com/example/backend/review/controller/ReviewController.java
backend/src/main/java/com/example/backend/review/service/ReviewService.java

BTS-130 리뷰 작성은 로그인한 사용자만 가능하도록 변경

[fix] 리뷰 수정 기능 삭제

---

backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/main/java/com/example/backend/product/model/Product.java
backend/src/main/java/com/example/backend/util/HttpClientUtil.java

* 결제 검증 과정의 잘못된 로직 수정
* 환불 과정에서 누락된 POST 요청 body 추가

[FIx] 결제 검증 및 환불 관련 오류 수정

---

backend/src/main/java/com/example/backend/coupon/model/UserCoupon.java
backend/src/main/java/com/example/backend/order/controller/OrderController.java
backend/src/main/java/com/example/backend/order/model/OrderDetail.java
backend/src/main/java/com/example/backend/order/model/Orders.java
backend/src/main/java/com/example/backend/order/model/dto/OrderDetailRequestDto.java
backend/src/main/java/com/example/backend/order/model/dto/OrderDetailResponseDto.java
backend/src/main/java/com/example/backend/order/model/dto/OrderRequestDto.java
backend/src/main/java/com/example/backend/order/model/dto/OrderResponseDto.java
backend/src/main/java/com/example/backend/order/model/dto/OrderVerifyRequestDto.java
backend/src/main/java/com/example/backend/order/service/OrderService.java

BTS-153, 156
결제 시 사용자가 쿠폰을 사용했다면 사용 여부를 저장하고 할인된 가격을 적용한다. 사용한 쿠폰은 사용됨 상태로 변경한다.

[feat] 결제 시 사용자가 쿠폰을 사용했다면 할인

---

backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/main/java/com/example/backend/product/model/dto/ProductFilterRequestDto.java
backend/src/main/java/com/example/backend/product/service/ProductService.java

각종 스펙 엔티티 변경에 따른 dto, product 서비스 수정
BTS- 168 환불 진행 시 주문에 사용했던 쿠폰 사용여부 롤백

오류 수정 및 환불 절차에 따른 쿠폰 복원

---

backend/build.gradle
backend/src/main/java/com/example/backend/admin/controller/StatisticController.java
backend/src/main/java/com/example/backend/admin/model/TopSales.java
backend/src/main/java/com/example/backend/admin/model/TopWishList.java
backend/src/main/java/com/example/backend/admin/model/dto/StatisticsResponseDto.java
backend/src/main/java/com/example/backend/admin/model/dto/TopSalesResponseDto.java
backend/src/main/java/com/example/backend/admin/model/dto/TopWishlistResponseDto.java
backend/src/main/java/com/example/backend/admin/model/dto/ViewRequestDto.java
backend/src/main/java/com/example/backend/admin/service/StatisticsService.java
backend/src/main/java/com/example/backend/coupon/service/CouponService.java
backend/src/main/java/com/example/backend/order/repository/OrderDetailRepository.java
backend/src/main/java/com/example/backend/product/model/dto/ProductResponseDto.java
backend/src/main/java/com/example/backend/wishlist/repository/WishlistRepository.java
backend/src/main/resources/application.yml

[Fix] 제품 정보 DTO 일부 수정

---

backend/k8s/backend-cm.yml
backend/k8s/backend-deployment-blue.yml
backend/k8s/backend-deployment-green.yml
backend/k8s/backend-svc.yml

기존에 사용하던 쿠버네티스 파일 추가(블루 그린 배포 버전)

[feat] k8s 파일 추가

---

backend/src/main/java/com/example/backend/admin/service/StatisticsService.java

[Fix] 관리자 통계 - 위시리스트/판매량 없을 때 상위 제품 리스트 예외 처리

---

backend/src/main/java/com/example/backend/product/controller/ProductController.java

Reverts beyond-sw-camp/be12-fin-404Found-Tech-Up-BE#136

Revert "[Fix] 전체 사용자 페이지네이션 & 카테고리 별 보기 일부 구현"

---

.idea/modules.xml
.idea/modules/backend.test.iml
backend/src/test/java/com/example/backend/order/service/ProductStockConcurrencyFailureTest.java
backend/src/test/resources/application-test.yml

현재 100개의 재고 중 50명이 동시에 구매 시도 시 남은 재고가 95개(예상 재고 50개)로 표시.

재고 동시성 제어 테스트 코드 작성

---

backend/build.gradle
backend/src/main/java/com/example/backend/global/response/responseStatus/OrderResponseStatus.java
backend/src/main/java/com/example/backend/order/service/OrderService.java
backend/src/test/java/com/example/backend/order/service/ProductStockConcurrencySuccessTest.java
backend/src/test/resources/application-test.yml

[feat] 재고 동시성 제어 테스트 코드(제어 성공 버전) 작성 및 테스트 코드 기반 주문 기능 재고 차감 시 동시성 제어 가능하도록 수정

테스트 코드 추가 및 주문 기능 로직 변경

---

backend/src/main/java/com/example/backend/product/controller/ProductController.java
backend/src/main/java/com/example/backend/product/service/ProductService.java
backend/src/main/resources/application.yml
backend/src/test/java/com/example/backend/search/service/SearchLatencyTest.java

Elasticsearch의 경우와 비교 대조를 위해 추가

[Fix] 검색 - 레거시 API 카테고리 검색 추가

---

backend/src/main/java/com/example/backend/product/model/dto/ReducedProductResponseDto.java

ReducedProductResponseDto 이미지 필드 명칭: image -> images

[Fix] 제품 신상 - DTO 이미지 필드명 정정

---

backend/src/main/java/com/example/backend/config/WebMvcConfig.java

[fix] 리뷰 작성에 사용된 jacksondate가 인식 안되는 오류 수정
